language: python
python:
 - "3.6"

install: pip install -r requirements-dev.txt

matrix:
  include:
    - name: Black formatter
      script: black --check .
      after_failure: utils/travis_notify_unformatted.sh
